# DURING THE IMPORT, WE END UP WITH A "BRANCH" CALLED "TRUNK" 
# THIS:
#	1. FETCHES THE LATEST UPDATES FROM SVN
#	2. RESETS MASTER TO WHATEVER IS NOW IN TRUNK
#	3. DELETES THE TRUNK BRANCH (WE ONLY WANT MASTER GOING FORWARD)

git svn fetch
git reset --hard svn/trunk
git branch -d -r svn/trunk