# GENERATE A TEXT FILE OF EVERY SINGLE BRANCH IN THE REPO
# AFTER THIS COMMAND FINISHES, MODIFY THAT FILE
# LEAVE ONLY THE BRANCHES LISTED THAT YOU WANT TO DELETE.

git branch -a > ./list_of_branches_for_deletion.txt