# FINDS ALL THE BRANCHES THAT START WITH "RB-" (THESE WERE THE RELEASE BRANCHES IN SVN)
# MOVES THEM INTO A "FOLDER" CALLED "RELEASES" FOR ORGANIZATION
# MOST GIT GUIS WILL ALLOW COLLAPSING AT THIS LEVEL TO HIDE THEM IF YOU'VE ACTUALLY PULLED
# THEM ALL DOWN.

for rb in `git branch -a | grep "rb-"`; do
  newBranchName=${rb:4}
  git branch -m $rb releases/$newBranchName
done